### ISSUE TITLE
[BUG] Segmentation Fault when convert RWKV-3B

### ISSUE THREAD

**Issue by L-M-Sherlock** [harrisonvanderbyl/rwkv-onnx#2]
I locate the bug:

https://github.com/harrisonvanderbyl/rwkv-onnx/blob/5a601c7b254d20d7d9f4019083ff861f2d3df0af/opslist.py#L379-L383

When I converted the 3B model, the size of graph_def was larger than 3GB. Onnx couldn't deal with files larger than 2GB. Could we output RWKV layer by layer?

**Comment by harrisonvanderbyl** [comment]
this should work fine, as I am using external storage,
what are your version numbers for onnx/protobuf?

**Comment by harrisonvanderbyl** [comment]
After some testing, I have determined you need exactly protobuf 3.20.0

**Comment by L-M-Sherlock** [comment]
> this should work fine, as I am using external storage,
> what are your version numbers for onnx/protobuf?

Thanks for your reply. I used 3.19.4 before. I'm installing the latest version and will test it again.

**Comment by L-M-Sherlock** [comment]
```shell
# jarrettye @ Zen-Max in ~/Codes/rwkv-onnx on git:main x [10:12:39] C:139
$ protoc --version
libprotoc 3.20.3
(mps)
# jarrettye @ Zen-Max in ~/Codes/rwkv-onnx on git:main x [10:13:22]
$ python convert.py
2023-05-12 10:13:53.858 python[48277:33377218] +[CATransaction synchronize] called within transaction
embed  2048
Legacy RWKV
439
1325
('matvec_1763_out', ['layernorm_442_out', 'add_475_out', 'add_477_out', 'layernorm_482_out', 'maximum_468_out', 'layernorm_497_out', 'add_530_out', 'add_532_out', 'layernorm_537_out', 'maximum_523_out', 'layernorm_552_out', 'add_585_out', 'add_587_out', 'layernorm_592_out', 'maximum_578_out', 'layernorm_607_out', 'add_640_out', 'add_642_out', 'layernorm_647_out', 'maximum_633_out', 'layernorm_662_out', 'add_695_out', 'add_697_out', 'layernorm_702_out', 'maximum_688_out', 'layernorm_717_out', 'add_750_out', 'add_752_out', 'layernorm_757_out', 'maximum_743_out', 'layernorm_772_out', 'add_805_out', 'add_807_out', 'layernorm_812_out', 'maximum_798_out', 'layernorm_827_out', 'add_860_out', 'add_862_out', 'layernorm_867_out', 'maximum_853_out', 'layernorm_882_out', 'add_915_out', 'add_917_out', 'layernorm_922_out', 'maximum_908_out', 'layernorm_937_out', 'add_970_out', 'add_972_out', 'layernorm_977_out', 'maximum_963_out', 'layernorm_992_out', 'add_1025_out', 'add_1027_out', 'layernorm_1032_out', 'maximum_1018_out', 'layernorm_1047_out', 'add_1080_out', 'add_1082_out', 'layernorm_1087_out', 'maximum_1073_out', 'layernorm_1102_out', 'add_1135_out', 'add_1137_out', 'layernorm_1142_out', 'maximum_1128_out', 'layernorm_1157_out', 'add_1190_out', 'add_1192_out', 'layernorm_1197_out', 'maximum_1183_out', 'layernorm_1212_out', 'add_1245_out', 'add_1247_out', 'layernorm_1252_out', 'maximum_1238_out', 'layernorm_1267_out', 'add_1300_out', 'add_1302_out', 'layernorm_1307_out', 'maximum_1293_out', 'layernorm_1322_out', 'add_1355_out', 'add_1357_out', 'layernorm_1362_out', 'maximum_1348_out', 'layernorm_1377_out', 'add_1410_out', 'add_1412_out', 'layernorm_1417_out', 'maximum_1403_out', 'layernorm_1432_out', 'add_1465_out', 'add_1467_out', 'layernorm_1472_out', 'maximum_1458_out', 'layernorm_1487_out', 'add_1520_out', 'add_1522_out', 'layernorm_1527_out', 'maximum_1513_out', 'layernorm_1542_out', 'add_1575_out', 'add_1577_out', 'layernorm_1582_out', 'maximum_1568_out', 'layernorm_1597_out', 'add_1630_out', 'add_1632_out', 'layernorm_1637_out', 'maximum_1623_out', 'layernorm_1652_out', 'add_1685_out', 'add_1687_out', 'layernorm_1692_out', 'maximum_1678_out', 'layernorm_1707_out', 'add_1740_out', 'add_1742_out', 'layernorm_1747_out', 'maximum_1733_out'])
logits
state
graph_def
[1]    48277 segmentation fault  python convert.py
```

**Comment by L-M-Sherlock** [comment]
```shell
(mps)
# jarrettye @ Zen-Max in ~/Codes/rwkv-onnx on git:main x [10:19:39]
$ pip show onnx
Name: onnx
Version: 1.14.0
Summary: Open Neural Network Exchange
Home-page: https://github.com/onnx/onnx
Author: ONNX
Author-email: onnx-technical-discuss@lists.lfaidata.foundation
License: Apache License v2.0
Location: /opt/homebrew/Caskroom/miniforge/base/envs/mps/lib/python3.9/site-packages
Requires: numpy, protobuf, typing-extensions
Required-by:
(mps)
# jarrettye @ Zen-Max in ~/Codes/rwkv-onnx on git:main x [10:20:02]
$ pip show protobuf
Name: protobuf
Version: 4.22.3
Summary:
Home-page: https://developers.google.com/protocol-buffers/
Author: protobuf@googlegroups.com
Author-email: protobuf@googlegroups.com
License: 3-Clause BSD License
Location: /opt/homebrew/Caskroom/miniforge/base/envs/mps/lib/python3.9/site-packages
Requires:
Required-by: onnx, tensorboard
```

**Comment by L-M-Sherlock** [comment]
Oh, I degrade the pip protobuf from 4.22.3 to 3.20.3, and then it works!

**Comment by L-M-Sherlock** [comment]
Oh, I encounter a new problem:

```
$ python test.py
['CPUExecutionProvider']
['CPUExecutionProvider']
2023-05-12 13:03:51.256395 [W:onnxruntime:, graph.cc:3543 CleanUnusedInitializersAndNodeArgs] Removing initializer 'PreTrainedTensor_0'. It is not used by any node and should be removed from the model.
tensor(float16)
Downloading (…)olve/main/vocab.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.08M/1.08M [00:01<00:00, 716kB/s]
Downloading (…)olve/main/merges.txt: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 457k/457k [00:01<00:00, 331kB/s]
Downloading (…)/main/tokenizer.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.11M/2.11M [00:03<00:00, 607kB/s]
Downloading (…)lve/main/config.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 613/613 [00:00<00:00, 300kB/s]
Loaded prompt.
Traceback (most recent call last):
  File "/Users/jarrettye/Codes/rwkv-onnx/test.py", line 109, in <module>
    prompt = prompt+[npsample(logits)]
  File "/Users/jarrettye/Codes/rwkv-onnx/test.py", line 91, in npsample
    mout = np.random.choice(a=len(probs), p=probs)
  File "mtrand.pyx", line 935, in numpy.random.mtrand.RandomState.choice
ValueError: probabilities contain NaN
```

**Comment by harrisonvanderbyl** [comment]
hmm, might be an issue with running float16 on cpu, doing some testing now

**Comment by L-M-Sherlock** [comment]
I switch to a GPU device and get these errors:

```
available_providers: ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
tensor(float16)
2023-05-12 07:34:06.532460336 [W:onnxruntime:, graph.cc:3543 CleanUnusedInitializersAndNodeArgs] Removing initializer 'PreTrainedTensor_0'. It is not used by any node and should be removed from the model.
2023-05-12 07:34:06.532821641 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:614 CreateExecutionProviderInstance] Failed to create TensorrtExecutionProvider. Please reference https://onnxruntime.ai/docs/execution-providers/TensorRT-ExecutionProvider.html#requirements to ensure all dependencies are met.
2023-05-12 07:35:22.679121934 [E:onnxruntime:, sequential_executor.cc:514 ExecuteKernel] Non-zero status code returned while running Gather node. Name:'' Status Message: CUDA error cudaErrorNoKernelImageForDevice:no kernel image is available for execution on the device
```

It seems like a problem of cuda version?

**Comment by harrisonvanderbyl** [comment]
Might be missing some onnx runtime dependencies

**Comment by L-M-Sherlock** [comment]
Resolved. I used K80 in azure which doesn't support float16 and the version of Nvidia driver is too low, so I switched to M60 and work it out!

**Comment by L-M-Sherlock** [comment]
And fp32 is okay for CPU. Thanks for your great work!
